### PR TITLE
Fix/257 - Better feedback for empty projects

### PR DESCRIPTION
**Pull request by vogelino**
This PR adds:
- A default marker based on the location when there are no records with geolocation
- A better feedback message for the chart area when there are no devices

**Screenshot:**
Screen Shot 2021-06-01 at 1 41 58 PM

### CODE REVIEW

**Review by dnsos — APPROVED** [review]
Nice work @vogelino! 👏 

Just a side note: I feel that the GitHub UI mistakenly displays that this PR changes 27 files, however most of these changes are already on `main` if I see this correctly.

**Comment by dnsos** [comment]
Ah, just remembered that we decided to remove the subline "Die Autor:in ..."

**Comment by vogelino** [comment]
> Nice work @vogelino! 👏
> 
> Just a side note: I feel that the GitHub UI mistakenly displays that this PR changes 27 files, however, most of these changes are already on `main` if I see this correctly.

Right. Lots of this is because I merge a branch from an already merge PR into this branch before it was reviewed so I could reuse the geocoding code.

**Pull request merged**
