### PR TITLE
complete user profile page

### PR DESCRIPTION
**Pull request by lucasoeth**
- added additional tests
- on cancel reset form
- create and implement change email rpc
- fix typo in header

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
Great work! 👏

**Comment by lucasoeth** [comment]
@vogelino ich weis nicht wieso aber ein unrelated test zu meinem code fängt an zu failen

**Review by vogelino — APPROVED** [review]
Good! I should have seen them. Good that you did! :)

**Pull request merged**
