### PR TITLE
feat(isUsernameAlreadyTaken): Verify is the username is already taken

### PR DESCRIPTION
**Pull request by vogelino**
This PR adds a server-side verification to the UserInfoEdit component to ensures that the username isn't already taken.

### CODE REVIEW

**Review by lucasoeth — APPROVED** [review]
Everything looks great, thanks for implementing this feature. For some reason it flew over my head when creating the user page. Solid testing as usual, learned a lot!

Maybe consider returning the only count and not the rows in the isUsernameTaken hook for smaller response size. But this is just my hyperefficient C mind talking, so please ignore hehe

**Comment by vogelino** [comment]
> consider returning the only count and not the rows in the isUsernameTaken hook for smaller response size

Will do! Thx for the review! 🙏

**Review by dnsos — APPROVED** [review]
Looks great - very, very thorough work!

**Pull request merged**
