### PR TITLE
Feat/258 - How it works section on the landing page

### PR DESCRIPTION
**Pull request by vogelino**

### CODE REVIEW

**Comment by dnsos** [comment]
Hey @vogelino, I know this ist still draft, but I wanted to add an idea for handling the responsiveness of this section. Once we start lacking horizontal space, we could stack each step (Hardware, Sensoren etc.) on top of each other with the options (Arduino, Raspberry Pi etc.) next to the description text. In that case I would hide the arrow as we would go vertically. Example:

Screenshot 2021-06-01 at 19 03 54

(I think this would probably require restructuring the markup)

I could get involved in doing this, so feel free to assign me.

**Comment by vogelino** [comment]
> I wanted to add an idea for handling the responsiveness of this section

Great Idea! I had some ideas too. Maybe you're down for a pair programming session tomorrow where we try to figure that out? Right now the HTML structure works well on desktop but isn't easily adaptable to smaller devices. Let me know if you've got time.

**Review by dnsos — APPROVED** [review]
Great work @vogelino, let's merge this!

**Pull request merged**
